export enum ProphecyEnum {
  AirElement = "airelement",
  DeadEyes = "deadeyes",
  Destruction = "destruction",
  EarthElement = "earthelement",
  FireElement = "fireelement",
  Firearms = "firearms",
  Gunpowder = "gunpowder",
  Health = "health",
  Heaviness = "heaviness",
  Lightness = "lightness",
  NimbleFingers = "nimblefingers",
  Spells = "spells",
  Stamina = "stamina",
  Bull = "bull",
  Serpent = "serpent",
  Variety = "variety",
  WaterElement = "waterelement",
  Witchfire = "witchfire",
  // Hidden Prophecies
  Corrupted = "corrupted",
}
